before_script:
  - apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - apt-get update
  - apt-get install python3.6 python3-pip 
  - pip3 install virtualenv


stages:
  - build
  - test
  - deploy


.script: &build_script
  - python3 --version
  - ls

job1:
  stage: build
  script: *build_script
  only:
    - master