image: python:latest
image: redis:latest
image: rabbitmq:latest

before_script:
  - apt-get update
  - apt-get install -y python3-pip 
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - test
  # - build
  # - deploy

.script: &build_script
  - python3 --version
  - pip3 install -r requirements/local.txt
  - pip3 install -r requirements/test.txt
  - export DJANGO_SETTINGS_MODULE="config.settings.test"
  - pytest
  - coverage report -m

dev:
  stage: test
  script: *build_script
  services:
    - python:latest
    - redis:latest
    - rabbitmq:latest

  only:
    - master


# .script: &build_script2
#   - pip3 install -r requirements/production.txt


# prod:
#   stage: build
#   script: *build_script2
#   only:
#     - master