image: python:latest

before_script:
  - apt-get update
  - apt-get install -y python3-pip 
  - pip3 install virtualenv
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - build
  - test
  - deploy

.script: &build_script
  - python3 --version
  - pip3 install -r requirements/local.txt
  - pip3 install -r requirements/test.txt
  - pytest
  - coverage report -m

dev:
  stage: test
  script: *build_script
  only:
    - master


.script: &build_script2
  - pip3 install -r requirements/production.txt


prod:
  stage: build
  script: *build_script2
  only:
    - master