# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
    ]
