# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.URLField(default='https://www.gravatar.com/avatar/<libgravatar.Gravatar object at 0x7f3fe85f1ac8>?d=identicon'),
        ),
    ]
