# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(default='https://www.gravatar.com/avatar/<libgravatar.Gravatar object at 0x7fe63fd9eac8>?d=identicon'),
        ),
    ]
