# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180417_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
