# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180131_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(default=''),
        ),
    ]
