# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofilesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesettings',
            name='currency_details',
            field=models.TextField(default='', max_length=200, verbose_name='Currency Details'),
        ),
    ]
