# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180206_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileSettings',
        ),
    ]
