# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-18 15:00
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import packages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('kg', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), packages.models.onlyFiveRangeValidator])),
                ('quanity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('group', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='items_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.ItemsList'),
        ),
    ]
