# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 09:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('place', models.CharField(max_length=20)),
                ('group', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemlist_USERMODEL', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthBudgetAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_year', models.DateField(default=datetime.date(2018, 1, 1))),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mba_USERMODEL', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='items_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.ItemsList'),
        ),
        migrations.AlterUniqueTogether(
            name='monthbudgetamount',
            unique_together=set([('month_year', 'user')]),
        ),
    ]
