# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemslist',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
