# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
