# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_itemslist_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemslist',
            name='total_amount',
        ),
    ]
