# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0002_auto_20180205_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_details', models.TextField(default='', max_length=100)),
                ('active_patym', models.CharField(max_length=1)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
