# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packagesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesettings',
            name='active_patym',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
