# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20180207_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesettings',
            name='active_patym',
        ),
        migrations.AddField(
            model_name='packagesettings',
            name='active_paytm',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1),
        ),
    ]
