# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_itemslist_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
