# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20180207_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesettings',
            name='active_paytm',
        ),
        migrations.AddField(
            model_name='itemslist',
            name='payment_type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='packagesettings',
            name='force_mba',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
