# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20180107_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthBudgetAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_year', models.DateField(default=datetime.date(2018, 1, 1), unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemslist',
            options={'get_latest_by': ['-date'], 'ordering': ['-id']},
        ),
    ]
