# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20180207_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagesettings',
            old_name='force_mba',
            new_name='force_mba_update',
        ),
    ]
