# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20180112_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
