# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20180207_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesettings',
            name='currency_details',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
