# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_packagesettings_new_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesettings',
            name='new_settings',
        ),
        migrations.AddField(
            model_name='packagesettings',
            name='active_paytm',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
