# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20180123_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='user_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
