# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20180210_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesettings',
            name='entry_type',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='packagesettings',
            name='active_paytm',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
