# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 17:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0010_auto_20180123_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemlist_USERMODEL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='month_year',
            field=models.DateField(default=datetime.date(2018, 1, 1)),
        ),
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mba_USERMODEL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monthbudgetamount',
            unique_together=set([('month_year', 'user_id')]),
        ),
    ]
