# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_auto_20180210_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemslist',
            old_name='payment_type',
            new_name='entry_type',
        ),
        migrations.RemoveField(
            model_name='packagesettings',
            name='entry_type',
        ),
    ]
