# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_auto_20180210_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesettings',
            name='paytm_type',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='itemslist',
            name='entry_type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
