# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_auto_20180214_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='group',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='itemslist',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemslist',
            name='place',
            field=models.CharField(max_length=50),
        ),
    ]
