# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_auto_20180223_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesettings',
            name='paytm_type',
        ),
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='month_year',
            field=models.DateField(default=datetime.date(2018, 3, 1)),
        ),
    ]
