# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 08:03
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_auto_20180317_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemslist',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.RegexValidator('%Y-%m-%d')]),
        ),
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='month_year',
            field=models.DateField(default=datetime.date(2018, 3, 1), validators=[django.core.validators.RegexValidator('%Y-%m-%d')]),
        ),
    ]
