# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_auto_20180319_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesettings',
            name='geoloc_interval',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
