# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 17:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_packagesettings_geoloc_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='month_year',
            field=models.DateField(default=datetime.date(2018, 4, 1), validators=[django.core.validators.RegexValidator('%Y-%m-%d')]),
        ),
    ]
