# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 11:35
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_auto_20180404_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthbudgetamount',
            name='month_year',
            field=models.DateField(default=datetime.date(2018, 4, 1), validators=[django.core.validators.RegexValidator('(19|20)\\d\\d([- /.])(0[1-9]|1[012])\\2(0[1-9]|[12][0-9]|3[01])')]),
        ),
        migrations.AlterField(
            model_name='packagesettings',
            name='currency_details',
            field=models.CharField(blank=True, default='USD', max_length=5),
        ),
    ]
